server:
    port: 8080
spring:
    profiles:
        active: dev
    application:
               name:springboot-rabbitmq
    rabbitmq:
           publisher-confirms: true
           virtual-host: /
           listener:
                auto-startup: false


