server:
    port: 8080
spring:
    rabbitmq:
           host: 192.168.204.26
           port: 5672
           username: guest
           password: guest
           listener:
                 auto-startup: true
